### ISSUE TITLE
后端BaiduPCS-Go是否更新

### ISSUE THREAD

**Issue by CheerL** [Erope/baidupcs-web#1]
请问是仅仅对liuzhuoling2011/baidupcs-web的前端做了修补，还是同步更新了iikira/BaiduPCS-Go的内容？pcs-web已经好几个月没更新过后端了=_=

另外请问前后端是如何打包到一起的？

**Comment by Erope** [comment]
没有跟着iikira的commit走，后端是更新的，在我BaiduPCS库里面https://github.com/Erope/BaiduPCS-Go

不跟进原作者的COMMIT的原因是准备放弃原作者的下载模块，预备迁移到aria2
前端需要编译出来，然后放到后端的一个文件夹里面，build.sh脚本里面有rice命令会把前端HTML放进去

**Comment by Erope** [comment]
前端文件夹 https://github.com/Erope/BaiduPCS-Go/tree/master/internal/pcsweb/dist
手机版一直没管也没更新，我觉得手机用这个可能有点奇怪

**Comment by Erope** [comment]
前端留的坑很多，不过我不是前端工程师，只能看着瞎修修
安全性也很成问题
