### ISSUE TITLE
3.7.1版不能下载，3.7.0可以

### ISSUE THREAD

**Issue by leoatchina** [Erope/baidupcs-web#2]
linux amd 64位版本
无论密码还是bu方式登陆
3.7.1版可以看到文件，但是下载会报not authenized 错误， 配置好aria2也如此
3.7.0版都可以下载，但是现在速度很慢

**Comment by Erope** [comment]
not authenized是被百度拉黑了，下载服务器不再是d0啊d9 d8之类，会变成限速服务器之类  
部分大文件会出现反热链-未认证等等情况  
这个其实和获取下载链接的代码有关系，目前获取下载链接的算法是原作者反编译了一个很老的百度安卓客户端，版本已经很旧了，所以会被针对; 而我并没有反编译的能力，也无法更新这个算法到最新的客户端。
3.7.0和3.7.1的下载内核其实没变化，Aria2功能的加入不影响原有下载引擎  
如果出现速度非常慢(所有任务加起来速度都不超过400k)  
那肯定是需要更换账户或者氪金到SVIP
如果有短时间大文件下载需求，还是建议先花几毛钱租个号

**Comment by leoatchina** [comment]
呃，问题是我是svip啊，而且3.7能下3.7.1不能下， 奇怪了

**Comment by Erope** [comment]
Emmmm 一般是SVIP应该不会出现这个问题
请先试试更换IP
然后试试官方客户端 能否正常加速下载
如果官方客户端可以正常下载但3.7.1不行的话，请QQ联系我，便于确定问题位置

**Comment by leoatchina** [comment]
在家里的NAS上3.7.1能正常下载，原来空间太紧张了，有1T数据没法下，现在从公司借到了。
不过现在不能几个任务并行下。

**Comment by Erope** [comment]
并行应该是没问题的
如果是用的Aria2 检查检查Aria2配置?
此外，获取的下载链接有效期不超过8小时，不建议一次性下载过多。
