### ISSUE TITLE
aria2如何指定并发数

### ISSUE THREAD

**Issue by garypang13** [Erope/baidupcs-web#3]
按照 ./BaiduPCS-Go -a -au "http://10.0.0.1:6800/jsonrpc" -as "xxxxxxxxxxxxxxxxxxxxx"
提示 并发数: 8 
请问如何增加并发数,谢谢.

**Comment by Erope** [comment]
在Web端的右上角 头像内有设置，设置内可以设置下载最大并发量。
最大并发量不会超过16，而且可能会被Aria2本身的配置所覆盖。
如果设置好Shell输出的是16并发，但Aria2并没能达到16并发，可能是配置被Aria2覆盖，也可能是百度关闭了部分链接。

**Comment by garypang13** [comment]
只要以aria2模式启动,web端设置的并发数就会被8覆盖,且无法再在web端修改,提示无权限.
我的Aria2是自己编译的魔改版,并发数不止16,

**Comment by Erope** [comment]
如果被8覆盖，那就证明无法读取配置文件或者配置文件被初始化了
如果无法修改，则证明没有对配置文件的写权限
建议先尝试使用root权限运行进行排障，然后再切换用户组

16并发数已经完全够用了，因为在没有限速以前，单线程限速500k/s以上，16线程就已经是9M/s了;
再多反而会加快限速。如果已经被限速了，那1k线程也没用。

**Comment by garypang13** [comment]
可以了,感谢,希望后续能增加在web界面配置aria2的选项.

**Comment by Erope** [comment]
> 可以了,感谢,希望后续能增加在web界面配置aria2的选项.

挠挠头，我倒是也想整，但奈何不会写前端...只会修修补补不会新增功能
